### ISSUE TITLE
FloodForge exits immediately on Arch Linux (w/ XFCE4) with Error 1

### ISSUE THREAD

**Issue by Suzriel** [Haizlbliek/FloodForge#3]
I can't build FloodForge on Linux as it exits very quickly.

Here is the build log from the terminal:
`[user@pc FloodForge-1.2]$ ./Build.sh
[INF] Updating header dependency graph...
[CXX] src/glad.c
[CXX] src/Draw.cpp
[CXX] src/gl.cpp
[CXX] src/stb.cpp
[CXX] src/Theme.cpp
[CXX] src/Utils.cpp
src/Utils.cpp:16:9: warning: "M_PI" redefined
   16 | #define M_PI   3.141592653589
      |         ^~~~
In file included from /usr/include/c++/14.2.1/cmath:47,
                 from src/math/Vector.hpp:2,
                 from src/math/Matrix4.hpp:4,
                 from src/Draw.hpp:2,
                 from src/Utils.cpp:2:
/usr/include/math.h:1152:10: note: this is the location of the previous definition
 1152 | # define M_PI           3.14159265358979323846  /* pi */
      |          ^~~~
src/Utils.cpp:17:9: warning: "M_PI_2" redefined
   17 | #define M_PI_2 1.570796326795
      |         ^~~~~~
/usr/include/math.h:1153:10: note: this is the location of the previous definition
 1153 | # define M_PI_2         1.57079632679489661923  /* pi/2 */
      |          ^~~~~~
[CXX] src/Window.cpp
[CXX] src/world/AcronymPopup.cpp
[CXX] src/world/main.cpp
[CXX] src/world/MenuItems.cpp
[CXX] src/world/Room.cpp
[CXX] src/world/Shaders.cpp
[CXX] src/world/SubregionNewPopup.cpp
[CXX] src/font/Fonts.cpp
[CXX] src/math/Matrix4.cpp
[CXX] src/math/Vector.cpp
[CXX] src/popup/Popups.cpp
[LNK] build/FloodForge
build/resource.o:(.rsrc+0x98): dangerous relocation: R_AMD64_IMAGEBASE with __ImageBase undefined
build/resource.o:(.rsrc+0xa8): dangerous relocation: R_AMD64_IMAGEBASE with __ImageBase undefined
collect2: error: ld returned 1 exit status
make: *** [build/build.mk:42: build/FloodForge] Error 1
Compilation failed.
[user@pc FloodForge-1.2]$`

Second attempt to build:
`[LNK] build/FloodForge
build/resource.o:(.rsrc+0x98): dangerous relocation: R_AMD64_IMAGEBASE with __ImageBase undefined
build/resource.o:(.rsrc+0xa8): dangerous relocation: R_AMD64_IMAGEBASE with __ImageBase undefined
collect2: error: ld returned 1 exit status
make: *** [build/build.mk:42: build/FloodForge] Error 1
Compilation failed.`

And here is my neofetch (pc information) since I presume it'll be very relevant to the bug:
`user@pc
_-_-_-
OS: Arch Linux x86_64
Host: X670E Steel Legend
Kernel: 6.12.1-zen1-1-zen
Uptime: 1 hour, 21 mins
Packages: 1213 (pacman), 34 (flatpak)
Shell: bash 5.2.37
Resolution: 1920x1080
DE: Xfce 4.18
WM: Xfwm4
WM Theme: Default
Theme: Adwaita-dark [GTK2/3]
Icons: elementary [GTK2], Adwaita [GTK3]
Terminal: alacritty
CPU: AMD Ryzen 7 7700X (16) @ 5.573GHz
GPU: AMD ATI Radeon RX 6650 XT / 6700S / 6800S
GPU: AMD ATI 18:00.0 Raphael
Memory: 4012MiB / 31200MiB`

The cleaner logs with proper indentation/lines (in txt format):
[build log.txt](https://github.com/user-attachments/files/17972001/build.log.txt)

**Comment by Haizlbliek** [comment]
This should hopefully be fixed now due to the latest commit.
If it still doesn't work, feel free to respond here.

https://github.com/Haizlbliek/FloodForge/commit/6a56fa40ac034ffd578582cd1c66c5e814e94a3d

**Comment by Suzriel** [comment]
The issue seems to still be occurring.

Here is my first build log (from after the update)
`[user@pc FloodForge-1.2.1]$ ./Build.sh
[INF] Updating header dependency graph...
[CXX] src/glad.c
[CXX] src/Draw.cpp
[CXX] src/gl.cpp
[CXX] src/stb.cpp
[CXX] src/Theme.cpp
[CXX] src/Utils.cpp
[CXX] src/Window.cpp
[CXX] src/world/AcronymPopup.cpp
[CXX] src/world/main.cpp
[CXX] src/world/MenuItems.cpp
[CXX] src/world/Room.cpp
[CXX] src/world/Shaders.cpp
[CXX] src/world/SubregionNewPopup.cpp
[CXX] src/font/Fonts.cpp
[CXX] src/math/Matrix4.cpp
[CXX] src/math/Vector.cpp
[CXX] src/popup/Popups.cpp
[LNK] build/FloodForge
build/resource.o:(.rsrc+0x98): dangerous relocation: R_AMD64_IMAGEBASE with __ImageBase undefined
build/resource.o:(.rsrc+0xa8): dangerous relocation: R_AMD64_IMAGEBASE with __ImageBase undefined
collect2: error: ld returned 1 exit status
make: *** [build/build.mk:42: build/FloodForge] Error 1
Compilation failed.`

And here is my second build log
`[user@pc FloodForge-1.2.1]$ ./Build.sh
[LNK] build/FloodForge
build/resource.o:(.rsrc+0x98): dangerous relocation: R_AMD64_IMAGEBASE with __ImageBase undefined
build/resource.o:(.rsrc+0xa8): dangerous relocation: R_AMD64_IMAGEBASE with __ImageBase undefined
collect2: error: ld returned 1 exit status
make: *** [build/build.mk:42: build/FloodForge] Error 1
Compilation failed.`

And the raw console log
[build log 24-11-03.txt](https://github.com/user-attachments/files/17982654/build.log.24-11-03.txt)

This issue might be relevant, possibly the same thing is happening here or similar? https://github.com/bfgroup/b2/issues/382
